### ISSUE TITLE
Threema not working properly

### ISSUE THREAD

**Issue by karotte512** [AnnaDamm/franz-recipe-threema#1]
Every time I start Threema in Franz it says "Browser not supported". I also have to reload Threema every time I open my Laptop (this is not the case when I use Threema Web in the the web browser) and reenter my password.

**Comment by AnnaDamm** [comment]
Thanks for your report.

I found a workaround for it and will implement it as soon as i have the time.

(reminder for myself):
https://github.com/meetfranz/plugins/blob/master/docs/backend_api.md#user-content-overrideuseragent
or
``angular.element(document.querySelector('[ui-view]')).controller().$mdDialog.hide();``

**Comment by AnnaDamm** [comment]
Apparently, the message that the threema services provides is wrong. Actually the chrome version used by Franz is too old. Threema runs on chrome 61 and threema needs 65.
Rather than me hiding the message, it would be nicer for Franz to upgrade.

**Comment by AnnaDamm** [comment]
Please update to the newest Franz version 5.0.0-beta23
